create table Person(
                       id int generated by default as identity primary key,
                       name varchar(100) UNIQUE not null,
                       loan double precision not null,
                       interest double precision not null,
                       years int not null,
                       payment double precision
);